### ISSUE TITLE
[Anki Killstreaks] Error when starting Anki

### ISSUE THREAD

**Issue by Ankilli** [shigeyukey/my_addons#34]
Hey, I get this error since the last update:

Debug:

Anki 24.04.1 (ccd9ca1a)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-14.5-arm64-arm-64bit

Traceback (most recent call last):
  File "/Users/kili/Library/Application Support/Anki2/addons21/0amboss_addon/indicator.py", line 89, in toolbar_redraw
    toolbar.redraw()  # 2.1.28+
  File "aqt.toolbar", line 286, in redraw
  File "aqt.toolbar", line 406, in update_sync_status
  File "aqt.sync", line 59, in get_sync_status
  File "aqt.taskman", line 69, in run_in_background
  File "aqt.taskman", line 142, in _on_closures_pending
  File "aqt.taskman", line 86, in <lambda>
  File "aqt.operations", line 260, in wrapped_done
  File "aqt.deckbrowser", line 170, in success
  File "aqt.deckbrowser", line 201, in __renderPage
  File "_aqt.hooks", line 1778, in __call__
  File "/Users/kili/Library/Application Support/Anki2/addons21/1562475180/main.py", line 248, in inject_medals_with_js
    view(
  File "/Users/kili/Library/Application Support/Anki2/addons21/1562475180/views.py", line 30, in TodaysMedalsJS
    html=MedalsOverview(
  File "/Users/kili/Library/Application Support/Anki2/addons21/1562475180/views.py", line 114, in MedalsOverview
    template = Template(f.read())
  File "encodings.ascii", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 2140: ordinal not in range(128)

/// (deleted the list of all my addons here)

regards and thank you for continuing this project! :)

**Comment by shigeyukey** [comment]
Thanks for the feedback and error report, there was a small mistake that I corrected and uploaded to Ankiweb.

**Comment by shigeyukey** [comment]
If the problem continues to occur, please reopen the issue. Thank! :-)
