### ISSUE TITLE
[🐤AnkiPet ] Zerodivision error when starting up Ankipet for the first time 

### ISSUE THREAD

**Issue by hannahweber244** [shigeyukey/my_addons#52]
# Bug
I started up the add on after installing it for the first time and ran into the following error:

```

Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 5.15.2 PyQt 5.15.5
Platform: Windows-10-10.0.19045

Traceback (most recent call last):
  File "***\AppData\Roaming\Anki2\addons21\2026040256\__init__.py", line 36, in enterGame
    gm.showPet()
  File "***\AppData\Roaming\Anki2\addons21\2026040256\gameQt.py", line 61, in showPet
    text.setPlainText(self.statsDiag())
  File "***\AppData\Roaming\Anki2\addons21\2026040256\gameQt.py", line 112, in statsDiag
    stats = self.game.getTodayStats()
  File "***\AppData\Roaming\Anki2\addons21\2026040256\game.py", line 134, in getTodayStats
    return [to_do_recent,done_today,done_today/float(to_do_recent+done_today),self.tokens,self.reputation]
ZeroDivisionError: float division by zero

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Anki Note Linker ['1077002392', 2024-09-09T16:24, 'None', '']
AnkiPet - gamify your learning by caring for a pet Fixed by Shige ['2026040256', 2024-06-16T08:21, 'None', mod]
Graph View - Link notes and visualize connections Fixed by Shige ['1068714931', 2024-03-03T15:48, 'None', '']
Image Editor ['307397307', 2022-09-08T06:09, 'None', '']
Image Occlusion Enhanced ['1374772155', 2022-04-09T09:15, 'None', '']
Markdown input ['904999275', 2023-09-01T23:46, '2.2.3', '']
Math Delimiters Replacer LaTex MathJax  -  Fixed by Shige ['401047458', 2024-04-06T16:13, 'None', '']
More Decks Stats and Time Left ['1556734708', 2024-08-20T00:49, 'None', '']
Papercards - export  print flashcards to paper ['2042118948', 2024-04-06T20:32, 'None', '']
Review Heatmap ['1771074083', 2022-06-30T03:43, 'None', '']

===IDs of active AnkiWeb add-ons===
1068714931 1077002392 1374772155 1556734708 1771074083 2026040256 2042118948 307397307 401047458 904999275

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Auto Markdown - fix version ['15061497', 2021-06-19T14:14, 'None', '']
Markdown and KaTeX Support Rework - Code Highlighting Math ['1786114227', 2024-06-30T11:07, 'None', '']
Markdown and KaTeX Support ['1087328706', 2023-05-06T13:28, 'None', '']
Simple Markdown ['354124843', 2024-09-05T18:26, 'None', '']

``` 

# quick fix
It just runs into this, because I havent done any studying of cards today. I fixed it by studying one card. Not really a bother, but maybe this is something you want to fix :)

**Comment by shigeyukey** [comment]
Thanks for reporting the issue, I'll look into it.
