### ISSUE TITLE
📥Multi Deck Importer: UnicodeDecodeError 'utf-8' codec can't decode 

### ISSUE THREAD

**Issue by shigeyukey** [shigeyukey/my_addons#55]
> like 2024-09-28 on [📥Multi Deck Importer (Fixed by Shige)](https://ankiweb.net/shared/info/1563006742)
> Traceback (most recent call last):
>   File "anki.importing.apkg", line 40, in run
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 1: invalid start byte
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/Users/mac/Library/Application Support/Anki2/addons21/1563006742/__init__.py", line 77, in importFromFolder
>     importer.run()
>   File "anki.importing.apkg", line 42, in run
> anki.importing.anki2.MediaMapInvalid
> 
> I tried txt, CSV same problem happened here ✋
> It works fine with built-in Anki import File → import...

**Comment by shigeyukey** [comment]
> dislike 2025-08-27 on [📥Multi Deck Importer (Fixed by Shigeඞ)](https://ankiweb.net/shared/info/1563006742)
> Not working Shige 
> 
> Anki 25.02.5 (29192d15)  (ao)
> Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
> Platform: macOS-15.5-x86_64-i386-64bit
> 
> Traceback (most recent call last):
>   File "anki.importing.apkg", line 41, in run
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 1: invalid start byte
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/Users/username/Library/Application Support/Anki2/addons21/1563006742/__init__.py", line 77, in importFromFolder
>     importer.run()
>   File "anki.importing.apkg", line 43, in run
> anki.importing.anki2.MediaMapInvalid
> 
> ===Add-ons (active)===
> (add-on provided name [Add-on folder, installed at, version, is config changed])
> Multi Deck Importer Fixed by Shige ['1563006742', 2024-02-17T09:33, 'None', '']
> 
> ===IDs of active AnkiWeb add-ons===
> 1563006742
> 
> ===Add-ons (inactive)===
> (add-on provided name [Add-on folder, installed at, version, is config changed])
