### ISSUE TITLE
⏩️Skip Anki home and deck overview: not working

### ISSUE THREAD

**Issue by shigeyukey** [shigeyukey/my_addons#95]
> like 2024-12-14 on [⏩️Skip Anki home and deck overview (Customized by Shigeඞ)](https://ankiweb.net/shared/info/295525470)
> cool addon, but one problem:
> 
> Expected behaviour: on opening anking teleported to start deck, istantly in reviewer
> Actual behavior: on opening, goes straight to start deck deck overview, however anki seems to think we are in reviewer, we can use reviewer hotkey, and then we get the anki addon troubleshoot popup
> 
> Expected behaviour: when we are in anki home and we click on deck we are automatically in reviewer
> Actual behaviour: when we are in anki home and clikc on a deck we are automatically in reviewer, however using review shortcuts/or pressing the buttons does not advance to the next card (and troubleshoot popup appear)
> 
> Anki 24.06.3 (d678e393)  (ao)
> Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
> Platform: Linux-6.12.4-arch1-1-x86_64-with-glibc2.40
> 
> Traceback (most recent call last):
>   File "aqt.taskman", line 142, in _on_closures_pending
>   File "aqt.taskman", line 86, in <lambda>
>   File "aqt.taskman", line 106, in wrapped_done
>   File "aqt.operations", line 127, in wrapped_done
>   File "aqt.reviewer", line 551, in after_answer
>   File "aqt.reviewer", line 563, in _after_answering
>   File "aqt.reviewer", line 938, in check_timebox
>   File "anki.collection", line 1175, in timeboxReached
>   File "anki._legacy", line 80, in __getattr__
> AttributeError: 'Collection' object has no attribute '_startTime'

**Comment by shigeyukey** [comment]
https://forums.ankiweb.net/t/bug-skip-anki-home-and-deck-overview-customized-by-shige/53212
